cmake_minimum_required(VERSION 3.22.1)
project("mygbaemulator")

set(LIBMGBA_ONLY ON CACHE BOOL "Build only the core library")
set(BUILD_SHARED ON CACHE BOOL "Build shared library")
set(BUILD_STATIC OFF CACHE BOOL "Build static library")
set(DISABLE_FRONTENDS ON CACHE BOOL "Disable frontends")
set(ENABLE_SCRIPTING OFF CACHE BOOL "Disable scripting")
set(BUILD_GL OFF CACHE BOOL "Disable GL")
set(BUILD_GLES2 OFF CACHE BOOL "Disable GLES2")
set(BUILD_GLES3 OFF CACHE BOOL "Disable GLES3")
set(USE_EPOXY OFF CACHE BOOL "Disable epoxy")
set(USE_FFMPEG OFF CACHE BOOL "Disable FFMPEG")
set(USE_ZLIB OFF CACHE BOOL "Disable ZLIB")
set(USE_PNG OFF CACHE BOOL "Disable PNG")
set(USE_LIBZIP OFF CACHE BOOL "Disable LIBZIP")
set(USE_SQLITE3 OFF CACHE BOOL "Disable SQLITE3")
set(USE_ELF OFF CACHE BOOL "Disable ELF")
set(USE_LUA OFF CACHE BOOL "Disable Lua")

add_subdirectory(../../../mGBA-core mGBA-core)

add_library(${CMAKE_PROJECT_NAME} SHARED native-lib.cpp)
target_link_libraries(${CMAKE_PROJECT_NAME} mgba android log)
target_include_directories(${CMAKE_PROJECT_NAME} PRIVATE ../../../mGBA-core/include)
